# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  WDB\WdbContentConditions\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

#  WDB\WdbContentConditions\UserFunction\ClassA:
#    public: true